ports:
  - port: 8080
    visibility: public

tasks:
  - init: |
      pnpm install
    command: |
      pnpm install -g @withgraphite/graphite-cli
      gt repo init --trunk main --no-interactive
      gt user branch-date --disable
      gt user branch-replacement --set-dash
      gt user pager --set 'less -FRX'
      if [ "$GRAPHITE_TOKEN" != "" ]; then gt auth --token "$GRAPHITE_TOKEN"; fi
      (yes | gt dsg --no-verify --quiet $(git rev-parse --abbrev-ref HEAD)) || true
      sudo apt install tig
      pnpm run build
      pnpm run start
  - command: ''

gitConfig:
  alias.co: checkout
  alias.ci: commit
  alias.amend: 'commit --amend --reset-author --no-edit'
  core.autocrlf: input
  core.whitespace: blank-at-eol,blank-at-eof,indent-with-tab
  pull.rebase: 'false'

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
